"""
Clone Hero chart builder for drum transcriptions.

Converts transcription events (GM MIDI notes + timing) into a Clone Hero
chart zip file containing:
  - notes.chart  (the chart data)
  - song.ini     (song metadata)
"""
from __future__ import annotations

import io
import zipfile
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# GM MIDI → Clone Hero drum mapping
#
# Clone Hero ExpertDrums note numbers:
#   0  = Kick
#   1  = Red pad    (Snare)
#   2  = Yellow pad (Hi-Hat / Tom)
#   3  = Blue pad   (Tom / Cymbal)
#   4  = Green pad  (Cymbal / Tom)
#  32  = Expert+ Kick (double bass)
#  66  = Yellow cymbal marker  (pad 2 = cymbal)
#  67  = Blue cymbal marker    (pad 3 = cymbal)
#  68  = Green cymbal marker   (pad 4 = cymbal)
# ---------------------------------------------------------------------------

# Each entry: (chart_note, cymbal_marker or None)
GM_TO_CH: dict[int, tuple[int, int | None]] = {
    36: (0, None),    # Kick            → Kick
    35: (0, None),    # Acoustic Bass   → Kick
    38: (1, None),    # Snare           → Red
    40: (1, None),    # Electric Snare  → Red
    37: (1, None),    # Side Stick      → Red
    42: (2, 66),      # Closed Hi-Hat   → Yellow cymbal
    44: (2, 66),      # Pedal Hi-Hat    → Yellow cymbal
    46: (2, 66),      # Open Hi-Hat     → Yellow cymbal
    45: (3, None),    # Low Tom         → Blue tom
    43: (3, None),    # High Floor Tom  → Blue tom
    47: (3, None),    # Low-Mid Tom     → Blue tom
    48: (2, None),    # Hi-Mid Tom      → Yellow tom
    50: (2, None),    # High Tom        → Yellow tom
    49: (4, 68),      # Crash Cymbal 1  → Green cymbal
    57: (4, 68),      # Crash Cymbal 2  → Green cymbal
    51: (3, 67),      # Ride Cymbal     → Blue cymbal
    53: (3, 67),      # Ride Bell       → Blue cymbal
    52: (4, 68),      # Chinese Cymbal  → Green cymbal
    55: (4, 68),      # Splash Cymbal   → Green cymbal
}

# Fallback: map unknown notes to Red pad
_DEFAULT_CH = (1, None)

TICKS_PER_BEAT = 480


def build_chart_zip(
    events: list[dict],
    metadata: dict[str, Any],
    song_name: str = "Drum Transcription",
    song_wav: Path | None = None,
    drums_wav: Path | None = None,
    drumless_wav: Path | None = None,
) -> bytes:
    """
    Build a Clone Hero chart zip from transcription events.

    Parameters
    ----------
    events       : list of dicts with keys: note (GM MIDI), time (seconds), velocity
    metadata     : dict with bpm, beats_per_bar, beat_unit
    song_name    : display name for the chart
    song_wav     : path to the original full mix WAV (included as song.wav)
    drums_wav    : path to the drums-only WAV (included as drums.wav)
    drumless_wav : path to the drumless mix WAV (included as drumless.wav)

    Returns
    -------
    bytes of a zip file containing notes.chart and song.ini
    """
    bpm = metadata.get("bpm", 120.0)
    beats_per_bar = metadata.get("beats_per_bar", 4)

    beat_dur = 60.0 / bpm
    # 2 seconds of leading silence (standard for CH charts)
    leading_ticks = int(2.0 / beat_dur * TICKS_PER_BEAT)

    # --- SyncTrack ---
    sync_lines: list[str] = []
    sync_lines.append(f"  0 = TS {beats_per_bar}")
    sync_lines.append(f"  0 = B {int(bpm * 1000)}")
    sync_track = "\n".join(sync_lines) + "\n"

    # --- ExpertDrums ---
    note_lines: list[str] = []

    for ev in sorted(events, key=lambda e: e["time"]):
        gm_note = ev["note"]
        ch_note, cymbal = GM_TO_CH.get(gm_note, _DEFAULT_CH)

        tick = leading_ticks + int(ev["time"] / beat_dur * TICKS_PER_BEAT)

        note_lines.append(f"  {tick} = N {ch_note} 0")
        if cymbal is not None:
            note_lines.append(f"  {tick} = N {cymbal} 0")

    notes_track = "\n".join(note_lines) + "\n"

    # --- notes.chart ---
    chart_content = f"""[Song]
{{
  Name = "{song_name}"
  Charter = "Oahsnail"
  Offset = 0
  Resolution = {TICKS_PER_BEAT}
  Difficulty = 4
  PreviewStart = 0
  PreviewEnd = 10000
  Genre = "rock"
  MediaType = "cd"
  MusicStream = "song.ogg"
}}
[SyncTrack]
{{
{sync_track}}}
[ExpertDrums]
{{
{notes_track}}}
"""

    # --- song.ini ---
    ini_content = f"""[Song]
name = {song_name}
artist = Unknown
album = Unknown
genre = rock
charter = drum-transcriber
diff_drums = -1
loading_phrase = Generated by drum-transcriber

"""

    # --- Build zip ---
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("notes.chart", chart_content)
        zf.writestr("song.ini", ini_content)
        # Include audio files if they exist
        if song_wav and song_wav.exists():
            zf.write(song_wav, "song.wav")
        if drums_wav and drums_wav.exists():
            zf.write(drums_wav, "drums.wav")
        if drumless_wav and drumless_wav.exists():
            zf.write(drumless_wav, "drumless.wav")
    return buf.getvalue()
